server:
  port: 8080
  host: 0.0.0.0

client:
  connect-timeout-millis: 2000
  read-timeout-millis: 2000
  follow-redirects: true
  max-redirects: 5
  services:
    config:
      metrics:
        - type: METER
          name-format: "client.meter.overall"
        - type: TIMER
          # meter per method
          name-format: "client.meter.%1$s"
        - methods: ["GET", "PUT", "POST", "DELETE"]
          type: COUNTER
          name-format: "client.counter.%1$s.%2$s"

backend:
    url: http://activity:8080

debug:
  header: trace-debug-id

metrics:
  registries:
    - type: application
  key-performance-indicators:
    extended: true
    long-running:
      threshold-ms: 2000
tracing:
  enabled: true
  service: "hobby"
  protocol: "http"     # JAEGER_ENDPOINT (if not udp, http is expected and endpoint is filled)
  host: "jaeger:14250/api/traces"   # JAEGER_ENDPOINT
  paths:
    - path: "/metrics"
      enabled: true
    - path: "/health"
      enabled: true
    - path: "/api"
      enabled: true
  propagation: "jaeger" # JAEGER_PROPAGATION either "jaeger" or "b3"
  log-spans: true      # JAEGER_REPORTER_LOG_SPANS
  max-queue-size: 42    # JAEGER_REPORTER_MAX_QUEUE_SIZE
  flush-interval-ms: 10001 # JAEGER_REPORTER_FLUSH_INTERVAL

