---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 96059e271637ad9f7215eea1faa75adb4fdab46a
    app.quarkus.io/build-timestamp: 2022-04-08 - 18:42:00 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: activity
    app.kubernetes.io/version: 2.0.6-native
  name: activity
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: activity
    app.kubernetes.io/version: 2.0.6-native
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 96059e271637ad9f7215eea1faa75adb4fdab46a
    app.quarkus.io/build-timestamp: 2022-04-08 - 18:42:00 +0000
  labels:
    app.kubernetes.io/name: activity
    app.kubernetes.io/version: 2.0.6-native
  name: activity
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: activity
                port:
                  name: http
            path: /
            pathType: Prefix