apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: activity
  name: activity
spec:
  ports:
    - name: "8082"
      port: 80
      targetPort: 8082
  selector:
    io.kompose.service: activity
status:
  loadBalancer: {}
