apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 96059e271637ad9f7215eea1faa75adb4fdab46a
    app.quarkus.io/build-timestamp: 2022-04-08 - 18:50:44 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: hobby-frontend
    app.kubernetes.io/version: 2.0.6-native
  name: hobby-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hobby-frontend
      app.kubernetes.io/version: 2.0.6-native
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 96059e271637ad9f7215eea1faa75adb4fdab46a
        app.quarkus.io/build-timestamp: 2022-04-08 - 18:50:44 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: hobby-frontend
        app.kubernetes.io/version: 2.0.6-native
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/ammbra/hobby:2.0.6-native
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: hobby-frontend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
