apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: hobby
  name: hobby
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hobby
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: hobby
    spec:
      containers:
        - args:
            - -Dquarkus.opentelemetry.tracer.exporter.jaeger.endpoint=http://jaeger:14250/api/traces
            - -Dquarkus.http.port=8080
            - -Dorg.acme.entertainment.BackendService/mp-rest/url=http://activity:8082
          image: quay.io/anasandbox/hobby:2.0.6-native
          name: hobby
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
