apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: hobby-frontend
    app.kubernetes.io/version: 2.0.6
  name: hobby
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: hobby-frontend
    app.kubernetes.io/version: 2.0.6
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: hobby-frontend
    app.kubernetes.io/version: 2.0.6
  name: hobby-frontend
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: hobby
                port:
                  name: http
            path: /
            pathType: Prefix
