apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jaeger
    spec:
      containers:
        - args:
            - --query.ui-config
            - /etc/jaeger/jaeger-ui.json
            - --log-level
            - debug
            - --metrics-backend
            - prometheus
            - --metrics-http-route
            - /metrics
            - --sampling.strategies-file
            - /etc/jaeger/sampling_strategies.json
          env:
            - name: METRICS_STORAGE_TYPE
              value: prometheus
            - name: PROMETHEUS_SERVER_URL
              value: http://prometheus:9090
          image: quay.io/jaegertracing/all-in-one:latest
          name: jaeger
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 16686
            - containerPort: 5778
          resources: {}
          volumeMounts:
            - mountPath: /etc/jaeger
              name: jaeger-config-volume
      restartPolicy: Always
      volumes:
        - name: jaeger-config-volume
          configMap:
            defaultMode: 420
            name: jaeger-server-conf
status: {}
