apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  type: ClusterIP
  ports:
    - name: "5775"
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: http
      port: 14250
      targetPort: 14250
    - name: "14268"
      port: 14268
      targetPort: 14268
    - name: "6831"
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: "6832"
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "5778"
      port: 5778
  selector:
    io.kompose.service: jaeger
