kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
  name: prometheus
  labels:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: prometheus
  template:
    metadata:
      labels:
        deployment: prometheus
    spec:
      volumes:
        - name: prometheus-volume-1
          emptyDir: {}
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: prometheus-volume-1
              mountPath: /prometheus
            - mountPath: /etc/config
              name: prometheus-config-volume
          terminationMessagePolicy: File
          image: prom/prometheus:v2.41.0
          args:
            - '--config.file=/etc/config/prometheus.yml'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30